contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #covidww channel"
    url: https://nfcore.slack.com/channels/covidww
    about: Discussion about the nf-core/covidww pipeline
