name: map_plot
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-ggplot2=3.4.4
  - conda-forge::r-rcolorbrewer=1.1.3
  - conda-forge::r-scatterpie=0.2.1
  - conda-forge::r-tidygeocoder=1.0.5
  - conda-forge::r-maps=3.4.2